#!/usr/bin/env python3

import argparse
import os

import bentoctl_sagemaker

parser = argparse.ArgumentParser(
    description="Describe the Google Cloud Run deployment.",
    epilog="Check out https://github.com/bentoml/google-cloud-run-deploy#readme to know more",
)
parser.add_argument(
    "deployment_name", help="The name you want to use for your deployment"
)
parser.add_argument(
    "config_json",
    help="(optional) The config file for your deployment",
    default=os.path.join(os.getcwd(), "cloud_run_config.json"),
    nargs="?",
)
args = parser.parse_args()

deployment_spec = bentoctl_sagemaker.get_configuration_value(args.config_json)
bentoctl_sagemaker.describe(args.deployment_name, deployment_spec)

